server:
  port: 8081
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/vhr?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    druid:
      #监控统计拦截的filters
      filters: stat
      #配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20

  #  redis:
  #    database: 0
  #    host: 192.168.66.130
  #    port: 6379
  #    password: 123@456
  #    jedis:
  #      pool:
  #        max-active: 8
  #        max-idle: 8
  #        max-wait: -1ms
  #        min-idle: 0

  cache:
    cache-names: menus_cache
    redis:
      time-to-live: 1800s

  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
    open-in-view: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      #      enable_lazy_load_no_trans: true
      ddl-auto: validate
  #      naming:
  #        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
logging:
  level:
    org.hibernate: debug