server:
  port: 8082
spring:
  mail:
    host: smtp.qq.com
    protocol: smtp
    default-encoding: UTF-8
    password: vmllqnbdexqhbega
    username: 930441318@qq.com
    port: 587
    properties:
      mail:
        stmp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
    debug: true
  rabbitmq:
    username: guest
    password: guest
    host: 192.168.1.44
    port: 5672